package org.jellyfin.androidtv.ui.base.debug

/**
 * Screen identifiers for debug overlay badges.
 * Format: "NNN" id + short name displayed as "NNN·Name".
 */
object ScreenIds {
	// ── Startup / Auth (001-010) ──
	const val SPLASH_ID = "001"
	const val SPLASH_NAME = "Splash"
	const val SERVER_DISCOVERY_ID = "002"
	const val SERVER_DISCOVERY_NAME = "ServerDiscovery"
	const val SERVER_ADD_ID = "003"
	const val SERVER_ADD_NAME = "ServerAdd"
	const val USER_SELECT_ID = "004"
	const val USER_SELECT_NAME = "UserSelect"
	const val USER_LOGIN_ID = "005"
	const val USER_LOGIN_NAME = "UserLogin"
	const val QUICK_CONNECT_ID = "006"
	const val QUICK_CONNECT_NAME = "QuickConnect"
	const val PIN_LOGIN_ID = "007"
	const val PIN_LOGIN_NAME = "PinLogin"
	const val WELCOME_ID = "008"
	const val WELCOME_NAME = "Welcome"
	const val CONNECT_HELP_ID = "009"
	const val CONNECT_HELP_NAME = "ConnectHelp"

	// ── Home (011-020) ──
	const val HOME_ID = "011"
	const val HOME_NAME = "Home"

	// ── Browse (021-030) ──
	const val LIBRARY_BROWSE_ID = "021"
	const val LIBRARY_BROWSE_NAME = "LibraryBrowse"
	const val GENRES_GRID_ID = "022"
	const val GENRES_GRID_NAME = "GenresGrid"
	const val FOLDER_BROWSE_ID = "023"
	const val FOLDER_BROWSE_NAME = "FolderBrowse"
	const val BY_LETTER_ID = "024"
	const val BY_LETTER_NAME = "ByLetter"
	const val ALL_FAVORITES_ID = "025"
	const val ALL_FAVORITES_NAME = "AllFavorites"
	const val SEARCH_ID = "027"
	const val SEARCH_NAME = "Search"
	const val COLLECTION_BROWSE_ID = "028"
	const val COLLECTION_BROWSE_NAME = "CollectionBrowse"
	const val SUGGESTED_MOVIES_ID = "029"
	const val SUGGESTED_MOVIES_NAME = "SuggestedMovies"

	// ── Browse v2 (031-040) ──
	const val LIVE_TV_BROWSE_ID = "031"
	const val LIVE_TV_BROWSE_NAME = "LiveTV·Browse"
	const val MUSIC_BROWSE_ID = "032"
	const val MUSIC_BROWSE_NAME = "MusicBrowse"
	const val SCHEDULE_BROWSE_ID = "033"
	const val SCHEDULE_BROWSE_NAME = "ScheduleBrowse"
	const val RECORDINGS_BROWSE_ID = "034"
	const val RECORDINGS_BROWSE_NAME = "RecordingsBrowse"
	const val SERIES_RECORDINGS_ID = "035"
	const val SERIES_RECORDINGS_NAME = "SeriesRecordings"

	// ── Detail (041-050) ──
	const val ITEM_DETAIL_ID = "041"
	const val ITEM_DETAIL_NAME = "ItemDetail·v2"
	const val ITEM_LIST_ID = "042"
	const val ITEM_LIST_NAME = "ItemList"
	const val MUSIC_FAVORITES_ID = "043"
	const val MUSIC_FAVORITES_NAME = "MusicFavorites"

	// ── Player (051-060) ──
	const val VIDEO_PLAYER_ID = "051"
	const val VIDEO_PLAYER_NAME = "VideoPlayer"
	const val NEXT_UP_ID = "052"
	const val NEXT_UP_NAME = "NextUp"
	const val STILL_WATCHING_ID = "053"
	const val STILL_WATCHING_NAME = "StillWatching"
	const val AUDIO_PLAYER_ID = "054"
	const val AUDIO_PLAYER_NAME = "AudioPlayer"
	const val PHOTO_PLAYER_ID = "055"
	const val PHOTO_PLAYER_NAME = "PhotoPlayer"
	const val TRAILER_PLAYER_ID = "056"
	const val TRAILER_PLAYER_NAME = "TrailerPlayer"

	// ── Settings (071-090) ──
	const val SETTINGS_MAIN_ID = "071"
	const val SETTINGS_MAIN_NAME = "Settings·Main"
	const val SETTINGS_AUTH_ID = "072"
	const val SETTINGS_AUTH_NAME = "Settings·Auth"
	const val SETTINGS_CUSTOMIZATION_ID = "073"
	const val SETTINGS_CUSTOMIZATION_NAME = "Settings·Custom"
	const val SETTINGS_PLUGIN_ID = "074"
	const val SETTINGS_PLUGIN_NAME = "Settings·Plugin"
	const val SETTINGS_SCREENSAVER_ID = "075"
	const val SETTINGS_SCREENSAVER_NAME = "Settings·Screensaver"
	const val SETTINGS_PLAYBACK_ID = "076"
	const val SETTINGS_PLAYBACK_NAME = "Settings·Playback"
	const val SETTINGS_PLAYBACK_ADV_ID = "077"
	const val SETTINGS_PLAYBACK_ADV_NAME = "Settings·PlaybackAdv"
	const val SETTINGS_TELEMETRY_ID = "078"
	const val SETTINGS_TELEMETRY_NAME = "Settings·Telemetry"
	const val SETTINGS_DEVELOPER_ID = "079"
	const val SETTINGS_DEVELOPER_NAME = "Settings·Developer"
	const val SETTINGS_ABOUT_ID = "080"
	const val SETTINGS_ABOUT_NAME = "Settings·About"
	const val SETTINGS_LIBRARIES_ID = "081"
	const val SETTINGS_LIBRARIES_NAME = "Settings·Libraries"
	const val SETTINGS_JELLYSEERR_ID = "082"
	const val SETTINGS_JELLYSEERR_NAME = "Settings·Jellyseerr"
	const val SETTINGS_HOME_ID = "083"
	const val SETTINGS_HOME_NAME = "Settings·Home"
	const val SETTINGS_SUBTITLES_ID = "084"
	const val SETTINGS_SUBTITLES_NAME = "Settings·Subtitles"
	const val SETTINGS_PARENTAL_ID = "085"
	const val SETTINGS_PARENTAL_NAME = "Settings·Parental"
	const val SETTINGS_SYNCPLAY_ID = "086"
	const val SETTINGS_SYNCPLAY_NAME = "Settings·SyncPlay"
	const val SETTINGS_HOME_ROWS_IMG_ID = "087"
	const val SETTINGS_HOME_ROWS_IMG_NAME = "Settings·HomeRowsImg"
	const val SETTINGS_JELLYSEERR_ROWS_ID = "088"
	const val SETTINGS_JELLYSEERR_ROWS_NAME = "Settings·JellyseerrRows"
	const val SETTINGS_HOME_POSTER_ID = "089"
	const val SETTINGS_HOME_POSTER_NAME = "Settings·HomePoster"

	// ── Live TV (091-099) ──
	const val LIVE_TV_GUIDE_ID = "091"
	const val LIVE_TV_GUIDE_NAME = "LiveTV·Guide"

	// ── Jellyseerr (101-110) ──
	const val JELLYSEERR_BROWSE_BY_ID = "101"
	const val JELLYSEERR_BROWSE_BY_NAME = "Jellyseerr·BrowseBy"
	const val JELLYSEERR_MEDIA_ID = "102"
	const val JELLYSEERR_MEDIA_NAME = "Jellyseerr·Media"
	const val JELLYSEERR_PERSON_ID = "103"
	const val JELLYSEERR_PERSON_NAME = "Jellyseerr·Person"

	// ── Dialogs (111-120) ──
	const val ADD_TO_PLAYLIST_ID = "111"
	const val ADD_TO_PLAYLIST_NAME = "AddToPlaylist"
	const val CREATE_PLAYLIST_ID = "112"
	const val CREATE_PLAYLIST_NAME = "CreatePlaylist"
	const val SHUFFLE_OPTIONS_ID = "113"
	const val SHUFFLE_OPTIONS_NAME = "ShuffleOptions"
	const val SYNCPLAY_DIALOG_ID = "114"
	const val SYNCPLAY_DIALOG_NAME = "SyncPlayDialog"
}
