package org.jellyfin.androidtv.ui.settings

import org.jellyfin.androidtv.ui.settings.routes.allSettingsRoutes

object Routes {
	const val MAIN = "/"
	const val AUTHENTICATION = "/authentication"
	const val AUTHENTICATION_FROM_LOGIN = "/authentication+login"
	const val AUTHENTICATION_SERVER = "/authentication/server/{serverId}"
	const val AUTHENTICATION_SERVER_USER = "/authentication/server/{serverId}/user/{userId}"
	const val AUTHENTICATION_SORT_BY = "/authentication/sort-by"
	const val AUTHENTICATION_AUTO_SIGN_IN = "/authentication/auto-sign-in"
	const val AUTHENTICATION_PIN_CODE = "/authentication/pin-code"
	const val CUSTOMIZATION = "/customization"
	const val CUSTOMIZATION_THEME = "/customization/theme"
	const val CUSTOMIZATION_CLOCK = "/customization/clock"
	const val CUSTOMIZATION_WATCHED_INDICATOR = "/customization/watch-indicators"
	const val CUSTOMIZATION_SCREENSAVER = "/customization/screensaver"
	const val CUSTOMIZATION_SCREENSAVER_TIMEOUT = "/customization/screensaver/timeout"
	const val CUSTOMIZATION_SCREENSAVER_AGE_RATING = "/customization/screensaver/age-rating"
	const val CUSTOMIZATION_SCREENSAVER_MODE = "/customization/screensaver/mode"
	const val CUSTOMIZATION_SCREENSAVER_DIMMING = "/customization/screensaver/dimming"
	const val CUSTOMIZATION_SUBTITLES = "/customization/subtitles"
	const val CUSTOMIZATION_SUBTITLES_TEXT_COLOR = "/customization/subtitles/text-color"
	const val CUSTOMIZATION_SUBTITLES_BACKGROUND_COLOR = "/customization/subtitles/background-color"
	const val CUSTOMIZATION_SUBTITLES_EDGE_COLOR = "/customization/subtitles/edge-color"
	const val LIBRARIES = "/libraries"
	const val LIBRARIES_DISPLAY = "/libraries/display/{itemId}/{displayPreferencesId}/{serverId}/{userId}"
	const val LIBRARIES_DISPLAY_IMAGE_SIZE = "/libraries/display/{itemId}/{displayPreferencesId}/{serverId}/{userId}/image-size"
	const val LIBRARIES_DISPLAY_IMAGE_TYPE = "/libraries/display/{itemId}/{displayPreferencesId}/{serverId}/{userId}/image-type"
	const val LIBRARIES_DISPLAY_GRID = "/libraries/display/{itemId}/{displayPreferencesId}/{serverId}/{userId}/grid"
	const val HOME = "/home"
	const val HOME_POSTER_SIZE = "/home/poster-size"
	const val HOME_ROWS_IMAGE_TYPE = "/home/rows-image-type"
	const val LIVETV_GUIDE_FILTERS = "/livetv/guide/filters"
	const val LIVETV_GUIDE_OPTIONS = "/livetv/guide/options"
	const val LIVETV_GUIDE_CHANNEL_ORDER = "/livetv/guide/channel-order"
	const val PLAYBACK = "/playback"
	const val PLAYBACK_PLAYER = "/playback/player"
	const val PLAYBACK_NEXT_UP = "/playback/next-up"
	const val PLAYBACK_NEXT_UP_BEHAVIOR = "/playback/next-up/behavior"
	const val PLAYBACK_INACTIVITY_PROMPT = "/playback/inactivity-prompt"
	const val PLAYBACK_PREROLLS = "/playback/prerolls"
	const val PLAYBACK_MEDIA_SEGMENTS = "/playback/media-segments"
	const val PLAYBACK_MEDIA_SEGMENT = "/playback/media-segments/{segmentType}"
	const val PLAYBACK_ADVANCED = "/playback/advanced"
	const val PLAYBACK_RESUME_SUBTRACT_DURATION = "/playback/resume-subtract-duration"
	const val PLAYBACK_MAX_BITRATE = "/playback/max-bitrate"
	const val PLAYBACK_MAX_RESOLUTION = "/playback/max-resolution"
	const val PLAYBACK_REFRESH_RATE_SWITCHING_BEHAVIOR = "/playback/refresh-rate-switching-behavior"
	const val PLAYBACK_ZOOM_MODE = "/playback/zoom-mode"
	const val PLAYBACK_AUDIO_BEHAVIOR = "/playback/audio-behavior"
	const val JELLYSEERR = "/jellyseerr"
	const val JELLYSEERR_ROWS = "/jellyseerr/rows"
	const val PLUGIN = "/plugin"
	const val VEGAFOX_NAVBAR_POSITION = "/vegafox/navbar-position"
	const val VEGAFOX_SHUFFLE_CONTENT_TYPE = "/vegafox/shuffle-content-type"
	const val VEGAFOX_MEDIA_BAR_CONTENT_TYPE = "/vegafox/media-bar-content-type"
	const val VEGAFOX_MEDIA_BAR_ITEM_COUNT = "/vegafox/media-bar-item-count"
	const val VEGAFOX_MEDIA_BAR_OPACITY = "/vegafox/media-bar-opacity"
	const val VEGAFOX_MEDIA_BAR_COLOR = "/vegafox/media-bar-color"
	const val VEGAFOX_THEME_MUSIC_VOLUME = "/vegafox/theme-music-volume"

	const val VEGAFOX_DETAILS_BLUR = "/vegafox/details-blur"
	const val VEGAFOX_BROWSING_BLUR = "/vegafox/browsing-blur"
	const val VEGAFOX_PARENTAL_CONTROLS = "/vegafox/parental-controls"
	const val VEGAFOX_SYNCPLAY = "/vegafox/syncplay"
	const val VEGAFOX_SYNCPLAY_MIN_DELAY = "/vegafox/syncplay/min-delay-speed-to-sync"
	const val VEGAFOX_SYNCPLAY_MAX_DELAY = "/vegafox/syncplay/max-delay-speed-to-sync"
	const val VEGAFOX_SYNCPLAY_DURATION = "/vegafox/syncplay/speed-to-sync-duration"
	const val VEGAFOX_SYNCPLAY_MIN_DELAY_SKIP = "/vegafox/syncplay/min-delay-skip-to-sync"
	const val VEGAFOX_SYNCPLAY_EXTRA_OFFSET = "/vegafox/syncplay/extra-time-offset"
	const val DEVELOPER = "/developer"
	const val ABOUT = "/about"
	const val LICENSES = "/licenses"
	const val LICENSE = "/license/{artifactId}"
}

val routes = allSettingsRoutes
